### ISSUE TITLE
API call error when jet aircraft is equipped

### ISSUE THREAD

**Issue by LostLogia4** [KC3Kai/KC3Kai#1664]
KC3 Kai - 30.12.1

I got this notification whenever jet aircraft was equipped:

"It seems there was an error when we tried to handle the game data for api_req_kaisou/slot_exchange_index. Game API might have changed, so some features might be broken or inaccurate"

**Comment by LostLogia4** [comment]
The error from the devtools
```
objects.js:8 TypeError: Cannot read property '0' of undefined
    at window.KC3Gear.KC3Gear.fighterVeteran (chrome-extension://hkgmldnainaglpjngpajnnjfhpdjkohh/library/objects.js:2:1286)
    at window.KC3Ship.KC3Ship.fighterVeteran (chrome-extension://hkgmldnainaglpjngpajnnjfhpdjkohh/library/objects.js:12:7681)
    at Array.map (native)
    at window.KC3Fleet.KC3Fleet.fighterVeteran (chrome-extension://hkgmldnainaglpjngpajnnjfhpdjkohh/library/objects.js:1:4388)
    at window.KC3Fleet.KC3Fleet.fighterPowerText (chrome-extension://hkgmldnainaglpjngpajnnjfhpdjkohh/library/objects.js:1:4794)
    at Object.Fleet (chrome-extension://hkgmldnainaglpjngpajnnjfhpdjkohh/pages/devtools/themes/natsuiro/natsuiro.js:1:26878)
    at chrome-extension://hkgmldnainaglpjngpajnnjfhpdjkohh/pages/devtools/themes/natsuiro/natsuiro.js:1:17495
    at Function.<anonymous> (chrome-extension://hkgmldnainaglpjngpajnnjfhpdjkohh/library/modules/Network.js:1:737)
    at Function.each (chrome-extension://hkgmldnainaglpjngpajnnjfhpdjkohh/assets/js/global.js:1:2882)
    at Object.trigger (chrome-extension://hkgmldnainaglpjngpajnnjfhpdjkohh/library/modules/Network.js:1:699)KC3Request.process @ objects.js:8(anonymous function) @ Network.js:1(anonymous function) @ objects.js:8callbackWrapper @ VM121:35_onCallback @ VM121:165_onMessage @ VM121:167
```
```
objects.js:2 Uncaught TypeError: Cannot read property '0' of undefined(…)KC3Gear.fighterVeteran @ objects.js:2KC3Ship.fighterVeteran @ objects.js:12KC3Fleet.fighterVeteran @ objects.js:1KC3Fleet.fighterPowerText @ objects.js:1Fleet @ natsuiro.js:1(anonymous function) @ natsuiro.js:1(anonymous function) @ Network.js:1each @ global.js:1trigger @ Network.js:1api_req_kaisou/slot_exchange_index @ Kcsapi.js:1KC3Request.process @ objects.js:8(anonymous function) @ Network.js:1(anonymous function) @ objects.js:8callbackWrapper @ VM121:35_onCallback @ VM121:165_onMessage @ VM121:167
```

**Comment by sinsinpub** [comment]
it is expected issue. just need to update air power bonus in Config to add for new type id 57

**Comment by LostLogia4** [comment]
I'll simply paste the regular bomber value for now.
https://github.com/KC3Kai/KC3Kai/commit/e54d7426b0f9fbe1396a0979290ebb74485380d1

**Comment by sinsinpub** [comment]
have improved codes to fall back to fail-safe when default type 57 not ready.

**Comment by Tedster59** [comment]
I got my jet earlier today, here's some API of equipping planes to CVB while jet is equipped, PvP battle, swapping fleet around while CVB with jet equipped, and a 1-1 sortie.
[Jets.zip](https://github.com/KC3Kai/KC3Kai/files/650483/Jets.zip)

recorded using the API recorder built into the dev version.

**Comment by LostLogia4** [comment]
Problem was caused by the jet fighter-bomber's air power being undefined. What we need is the air power from the jet aircraft, which isn't available from API.

**Comment by dragonjet** [comment]
for those who want the fix without webstore update, fighter power JSON can be changed in settings. just copy from
https://github.com/KC3Kai/KC3Kai/commit/e54d7426b0f9fbe1396a0979290ebb74485380d1
https://github.com/KC3Kai/KC3Kai/commit/1aa87eb5af8e46ccd8b57690c8d4d994d8b65705

this also means we need to bump the `version` in ConfigManager to that their settings will be reset. Unfortunately by making this editable in settings, this means the old one is saved in their local storage and will not be updated even if we update the ConfigManager.

**Comment by sinsinpub** [comment]
@dragonjet local setting (of the air power property only) will be reset now, see commit 08735e3

**Comment by Javran** [comment]
bumping this issue, I think this should have been fixed? If so we can close this issue.

**Comment by LostLogia4** [comment]
It's already been resolved. so I'll close it.
