### ISSUE TITLE
ReferenceError: localMaps is not defined at Object.api_get_member/mapinfo

### ISSUE THREAD

**Issue by ljsebald** [KC3Kai/KC3Kai#2052]
With webstore release of 31.6.3, I'm now getting an error when opening up the map list for sortieing.

It appears that it is related to these two commits:
72e01284d5757454f4d9874fff560c1eff1f346d and fa7ff60908cf4a4bd5101c6d83811db838100bf8

Specifically in the block between lines 1837 and 1842 (the only place where localMaps is ever being referred to). I suspect these two references  are typos and localMap was meant instead.

**Comment by ztjal** [comment]
Same problem.
---------------------------------------------------------------------------
ReferenceError: localMaps is not defined
    at Object.api_get_member/mapinfo (chrome-extension://hkgmldnainaglpjngpajnnjfhpdjkohh/library/modules/Kcsapi.js:2:4533)
    at window.KC3Request.KC3Request.process (chrome-extension://hkgmldnainaglpjngpajnnjfhpdjkohh/library/objects.js:9:2310)
    at chrome-extension://hkgmldnainaglpjngpajnnjfhpdjkohh/library/modules/Network.js:1:1569
    at chrome-extension://hkgmldnainaglpjngpajnnjfhpdjkohh/library/objects.js:9:877
    at callbackWrapper (<anonymous>:35:2)
    at ExtensionServerClient._onCallback (<anonymous>:173:133)
    at ExtensionServerClient._onMessage (<anonymous>:175:9)
---------------------------------------------------------------------------
Click "出擊" every time, i hate it...

**Comment by gravyboatcapt** [comment]
Same thing here 31.6.3
"ReferenceError: localMaps is not defined\n    at Object.api_get_member/mapinfo
