### ISSUE TITLE
api_req_sortie/battle error

### ISSUE THREAD

**Issue by ztjal** [KC3Kai/KC3Kai#2233]
'Compass and Battle Data' work error, but not every time.
=============================
{"title":"KC3改遭遇游戏数据错误","message":"在尝试处理 api_req_sortie/battle 游戏数据时遇到错误，这可能是游戏API变化导致的，一些功能可能不准确或工作异常。","stack":"TypeError: Cannot read property '0' of undefined\n    
at window.KC3Ship.KC3Ship.calcJetsSteelCost (chrome-extension://hkgmldnainaglpjngpajnnjfhpdjkohh/library/objects.js:14:8414)\n    
at window.KC3Fleet.KC3Fleet.calcJetsSteelCost (chrome-extension://hkgmldnainaglpjngpajnnjfhpdjkohh/library/objects.js:2:9051)\n    
at window.KC3Node.KC3Node.engage (chrome-extension://hkgmldnainaglpjngpajnnjfhpdjkohh/library/objects.js:6:9635)\n    
at Object.engageBattle (chrome-extension://hkgmldnainaglpjngpajnnjfhpdjkohh/library/managers.js:8:4691)\n    
at Object.api_req_sortie/battle (chrome-extension://hkgmldnainaglpjngpajnnjfhpdjkohh/library/modules/Kcsapi.js:1:20809)\n    
at window.KC3Request.KC3Request.process (chrome-extension://hkgmldnainaglpjngpajnnjfhpdjkohh/library/objects.js:10:2418)\n    
at chrome-extension://hkgmldnainaglpjngpajnnjfhpdjkohh/library/modules/Network.js:1:1569\n    
at chrome-extension://hkgmldnainaglpjngpajnnjfhpdjkohh/library/objects.js:10:956\n    
at callbackWrapper (<anonymous>:17:89)\n    
at ExtensionServerClient._onCallback (<anonymous>:73:649)","request":"{\"url\":\"http://203.104.209.55/kcsapi/api_req_sortie/battle\",\"headers\":{\"Date\":。。。。。too long。。。。

**Comment by mikenzb** [comment]
There should be a error report you should be able to download, could you please upload that error report as well as your KC3 version number.

**Comment by ztjal** [comment]
[KC3-Error-1505550860.zip](https://github.com/KC3Kai/KC3Kai/files/1308186/KC3-Error-1505550860.zip)

**Comment by ztjal** [comment]
on that time , i'm battle map 4-5.

**Comment by ztjal** [comment]
3-2: A ok.
4-5: C error , F ok , H error , M error.

**Comment by ztjal** [comment]
I think it might be N-5 problem.
In map 5-5, A, D, E, and N all go error.

**Comment by sinsinpub** [comment]
it's not about map or node. not supposed to happen if data not mess.
try this https://github.com/KC3Kai/KC3Kai/issues/2163#issuecomment-322090142

**Comment by ztjal** [comment]
yes ,i'm equip a 橘花改.
after delete the three localStorage, the problem is solved.
but why? i didn't do anything except clear history.

**Comment by sinsinpub** [comment]
what do u mean 'clear history'?

**Comment by ztjal** [comment]
the history should be user data, but the localStorage should be static data.

**Comment by ztjal** [comment]
api_req_sortie/battle error show again...

**Comment by ztjal** [comment]
but this time there was no error, no change ship or equip.
i'm fighting on map 5-5.

**Comment by mikenzb** [comment]
Any luck with the newer releases of KC3?

**Comment by ztjal** [comment]
this month's 4-5, 5-5 map hasn't been pass.
whatever the result is, i'll come back to report.

**Comment by ztjal** [comment]
ok, i passed those two maps, everything is right.
