### ISSUE TITLE
Crafting causes an API error

### ISSUE THREAD

**Issue by Sweeper777** [KC3Kai/KC3Kai#2901]
# Versions:

- Your Chrome version: 77.0.3865.90
- Your OS and its version: macOS Mojave 10.14.6
- 32bit or 64bit? 64bit
- Your KC3 Kai version: 34.0.6
- Which build you have tried running? webstore version

### Steps to reproduce:

Craft an equipment in the game

### Actual behaviour:

An API error shows up

### Error Report (if applicable):
```
{
   "title":"APIデータ処理エラー",
   "message":"[TsunDBSubmission] APIデータを処理する時に失敗しました。もしゲームAPIが変更されたなら、一部の機能が不具合になってしまったので、それを確認するためにご報告をお願いします。",
   "stack":"TypeError: Cannot read property 'split' of undefined\n    at Object.processDevelopment (chrome-extension://hkgmldnainaglpjngpajnnjfhpdjkohh/library/modules/TsunDBSubmission.js:1:24622)\n    at Object.processData (chrome-extension://hkgmldnainaglpjngpajnnjfhpdjkohh/library/modules/TsunDBSubmission.js:1:29786)\n    at chrome-extension://hkgmldnainaglpjngpajnnjfhpdjkohh/library/modules/Network.js:1:3984",
   "request":"{\"url\":\"http://203.104.209.134/kcsapi/api_req_kousyou/createitem\",\"headers\":{\"Date\":\"Mon, 30 Sep 2019 20:25:52 GMT\",\"Server\":\"nginx\",\"Connection\":\"keep-alive\",\"X-Powered-By\":\"PHP/5.3.3\",\"Content-Length\":\"221\",\"Content-Type\":\"text/plain\"},\"statusCode\":200}",
   "params":"{\"api_verno\":\"1\",\"api_item1\":\"20\",\"api_item2\":\"20\",\"api_item3\":\"10\",\"api_item4\":\"90\",\"api_multiple_flag\":\"0\"}",
   "response":{
      "api_result":1,
      "api_result_msg":"成功",
      "api_data":{
         "api_create_flag":0,
         "api_material":[
            86457,
            86344,
            123174,
            83955,
            842,
            1137,
            725,
            8
         ],
         "api_get_items":[
            {
               "api_id":-1,
               "api_slotitem_id":-1
            }
         ],
         "api_unset_items":null
      }
   },
   "serverUtc":1569875152000,
   "kc3Version":"KanColle Command Center 改 34.0.6",
   "dmmPlay":"true",
   "gameTabUrl":"http://www.dmm.com/netgame/social/-/gadgets/=/app_id=854854/",
   "userAgent":"Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/77.0.3865.90 Safari/537.36",
   "utc":1569875152218
}
```

[KC3-Error-1569875167.txt](https://github.com/KC3Kai/KC3Kai/files/3674633/KC3-Error-1569875167.txt)

**Comment by sorewachigauyo** [comment]
Fixed in https://github.com/KC3Kai/KC3Kai/pull/2900

**Comment by Sweeper777** [comment]
Ah, ok, I guess I didn't check the PRs...
